name: shortly-local
services:
  postgresql:
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "./storage/postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortly_db
      POSTGRES_PORT: 5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol
      - "15672:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - shortly_rabbitmq:/var/lib/rabbitmq


volumes:
  shortly_rabbitmq: