name: shortly-local
services:
  postgresql:
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "./storage/postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortly_db
      POSTGRES_PORT: 5432